#ifndef APPLICATION_ARCHITECTURE_TYPE
#define APPLICATION_ARCHITECTURE_TYPE

enum ApplicationArchitectureType
{
	APPLICATION_ARCHITECTURE_UNKNOWN,
	APPLICATION_ARCHITECTURE_X86_32,
	APPLICATION_ARCHITECTURE_X86_64,
	APPLICATION_ARCHITECTURE_ARM_64

};

#endif	  // APPLICATION_ARCHITECTURE_TYPE
