name: Upload artifact

on:
  workflow_dispatch:

jobs:
  macos:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-26, macos-26-intel]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Install Dependencies
        run: |
          brew install imagemagick qt@5 llvm@21

      - name: Setup Java 25
        run: |
          if [[ -n "$JAVA_HOME_25_arm" ]]; then
            JAVA_HOME=$JAVA_HOME_25_arm
          else
            JAVA_HOME=$JAVA_HOME_25_X64
          fi
          echo JAVA_HOME="${JAVA_HOME}" >> $GITHUB_ENV

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git "$HOME/vcpkg" && \
          VCPKG_ROOT="$HOME/vcpkg"
          echo VCPKG_ROOT="${VCPKG_ROOT}" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          LLVM_DIR=`brew --prefix llvm@21` && \
          QT5_DIR=`brew --prefix qt@5` && \
          cmake --preset=release -DQt5_DIR="${QT5_DIR}/lib/cmake/Qt5" \
            -DClang_DIR="${LLVM_DIR}/lib/cmake/clang" \
            -DBUILD_CXX_LANGUAGE_PACKAGE=ON \
            -DBUILD_JAVA_LANGUAGE_PACKAGE=ON \
            -DBUILD_PYTHON_LANGUAGE_PACKAGE=ON

      - name: Build the binary
        run: |
          cd build/release && \
          ninja Sourcetrail && \
          cd app && \
          ./bundle_install.sh && \
          echo ARTIFACT_NAME=`ls Sourcetrail*.dmg` >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ github.workspace }}/build/release/app/${{ env.ARTIFACT_NAME }}
          overwrite: true
